version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR..
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - aws ecr get-login-password --region cn-northwest-1 | docker login --username AWS --password-stdin 727897471807.dkr.ecr.cn-northwest-1.amazonaws.com.cn
      - cd byoc-build/training
      - bash build_and_push.sh airflow-lstm
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Docker image pushed